### ISSUE TITLE
Crazyswarm2 backend is not letting me sim

### ISSUE THREAD

**Issue by shaumikkalwit** [gtfactslab/CrazySim#26]
When I try to run the CrazySim one drone sim, this is what shows (left is gazebo CrazySim, right is crazyswarm2 backend):
![Image](https://github.com/user-attachments/assets/0e05ca8e-ceec-4934-9137-10d383f4dba2)

These are what the terminals output, crazysim doesnt output the udp which is concerning
![Image](https://github.com/user-attachments/assets/1b8ad3e8-2078-4d07-9b59-fa66997a6158)
![Image](https://github.com/user-attachments/assets/b7966e59-063a-4b89-a636-f137f3a1e540)

Here is my crazyflies.yaml file in crazyswarm2/crazyflie/config:
![Image](https://github.com/user-attachments/assets/fc117874-2811-4778-a90d-91e5ab61e886)

**Comment by llanesc** [comment]
I think you have motion capture enabled. Try this:
```yaml
robots:
  cf_1:
      enabled: true
      uri: udp://0.0.0.0:19850
      initial_position: [0.0, 0.0, 0.0]
      type: cf_sim

robot_types:
  cf_sim:
    motion_capture:
      enabled: false
    big_quad: false
    firmware_logging:
      enabled: true
      default_topics:
        pose:
          frequency: 10
```

**Comment by shaumikkalwit** [comment]
> I think you have motion capture enabled. Try this:
> 
> robots:
>   cf_1:
>       enabled: true
>       uri: udp://0.0.0.0:19850
>       initial_position: [0.0, 0.0, 0.0]
>       type: cf_sim
> 
> robot_types:
>   cf_sim:
>     motion_capture:
>       enabled: false
>     big_quad: false
>     firmware_logging:
>       enabled: true
>       default_topics:
>         pose:
>           frequency: 10

I just did that, still doesnt work. Same thing, just with this output in terminal running the backend 
![Image](https://github.com/user-attachments/assets/09fcc544-43a3-41b5-8778-13a92ad93d56)

but the gui window is still white and not working

**Comment by adbidwai** [comment]
@llanesc

**Comment by Tengau** [comment]
Hi, 

I get the same problem when running the launch file, except my error looks like it can't find a CrazyRadio and cf231. Is there a specific version of CrazySwarm being used? 
Error Message:
```
[INFO] [launch]: Default logging verbosity is set to INFO

[INFO] [motion_capture_tracking_node-1]: process started with pid [180093]

[INFO] [crazyflie_server.py-2]: process started with pid [180095]

[INFO] [teleop-3]: process started with pid [180097]

[INFO] [joy_node-4]: process started with pid [180099]

[INFO] [gui.py-5]: process started with pid [180101]

[teleop-3] [INFO] [1774038078.291227298] [teleop]: Mode changed to high_level

[motion_capture_tracking_node-1] logClouds=0

[crazyflie_server.py-2] Couldn't load link driver: Cannot find a Crazyradio Dongle

[crazyflie_server.py-2]

[crazyflie_server.py-2] Traceback (most recent call last):

[crazyflie_server.py-2] File "/home/tg/software/CrazySim/crazyflie-lib-python/cflib/drivers/crazyradio.py", line 124, in __init__

[crazyflie_server.py-2] device = _find_devices()[devid]

[crazyflie_server.py-2] IndexError: list index out of range

[crazyflie_server.py-2]

[crazyflie_server.py-2] During handling of the above exception, another exception occurred:

[crazyflie_server.py-2]

[crazyflie_server.py-2] Traceback (most recent call last):

[crazyflie_server.py-2] File "/home/tg/software/CrazySim/crazyflie-lib-python/cflib/crazyflie/__init__.py", line 248, in open_link

[crazyflie_server.py-2] self.link = cflib.crtp.get_link_driver(

[crazyflie_server.py-2] File "/home/tg/software/CrazySim/crazyflie-lib-python/cflib/crtp/__init__.py", line 99, in get_link_driver

[crazyflie_server.py-2] instance.connect(uri, radio_link_statistics_callback, link_error_callback)

[crazyflie_server.py-2] File "/home/tg/software/CrazySim/crazyflie-lib-python/cflib/crtp/radiodriver.py", line 267, in connect

[crazyflie_server.py-2] self._radio = RadioManager.open(devid)

[crazyflie_server.py-2] File "/home/tg/software/CrazySim/crazyflie-lib-python/cflib/crtp/radiodriver.py", line 224, in open

[crazyflie_server.py-2] shared_radio = _SharedRadio(devid)

[crazyflie_server.py-2] File "/home/tg/software/CrazySim/crazyflie-lib-python/cflib/crtp/radiodriver.py", line 147, in __init__

[crazyflie_server.py-2] self._radio = Crazyradio(devid=devid)

[crazyflie_server.py-2] File "/home/tg/software/CrazySim/crazyflie-lib-python/cflib/drivers/crazyradio.py", line 129, in __init__

[crazyflie_server.py-2] raise Exception('Cannot find a Crazyradio Dongle')

[crazyflie_server.py-2] Exception: Cannot find a Crazyradio Dongle

[crazyflie_server.py-2]

[crazyflie_server.py-2] [INFO] [1774038078.801309257] [crazyflie_server]: [cf231] connection Failed

[crazyflie_server.py-2] [INFO] [1774038078.802116698] [crazyflie_server]: [cf231] is disconnected!

[crazyflie_server.py-2] [INFO] [1774038078.802994979] [crazyflie_server]: Error!: One or more Crazyflies can not be found.

[crazyflie_server.py-2] [INFO] [1774038078.803546049] [crazyflie_server]: Check if you got the right URIs, if they are turned on or if your script have proper access to a Crazyradio PA

[INFO] [crazyflie_server.py-2]: process has finished cleanly [pid 180095]

[gui.py-5]

[gui.py-5] A module that was compiled using NumPy 1.x cannot be run in

[gui.py-5] NumPy 2.2.6 as it may crash. To support both 1.x and 2.x

[gui.py-5] versions of NumPy, modules must be compiled with NumPy 2.0.

 
```
crazyflies.yaml file:
```
fileversion: 3

robots:
  cf_1:
      enabled: true
      uri: udp://127.0.0.1:19850
      initial_position: [0.0, 0.0, 0.0]
      type: cf_sim

robot_types:
  cf_sim:
    motion_capture:
      tracking: "vendor"
    big_quad: false
    firmware_logging:
      enabled: true
      default_topics:
        pose:
          frequency: 10
```

Edit: I also tried your version with motion_capture set to false
